
# favicon
favicon: /img/favicon.ico

# rss
rss: /atom.xml

# main menu navigation
menu:
  Home: / || Home
  About: /about/ || About
  Archives: /archives/ || Archives

bio:
  I just want something to be simpler...

page_404:
  enable: true
  subtitle: 'Oops! Page not found.'

comments:
  enable: true
  type: waline # waline 
  button: true

#Waline https://waline.js.org
waline:
  serverURL: https://talk-blog.vercel.app # your waline serverURLs
  avatarCDN: # default is https://sdn.geekzu.org/avatar/
  avatar: monsterid # gravatar style https://zh-tw.gravatar.com/site/implement/images/#default-image
  placeholder: 'Let me know what you think！'

# stylesheets loaded in the <head>
stylesheets:
  - /css/main.css

# scripts loaded in the end of the body
scripts:
  - /js/main.js
