#---------------------------
# Global
#---------------------------

# 用于背景图
bgimg: /10_gettyimages-508748776_super_resized.jpg

# 背景图的色调强度，使用原始图片请填 100%
bgsat: 500%

# 背景图的模糊度，不模糊请填 0
bgblu: 20px

# 用于header、footer的颜色
hfcolor: '#26689e'

# 用于统计运行日期
buildtime: 2020-07-17

#---------------------------
# header & Footer
#---------------------------

# Header 的图像

headerimg:
  enable: true
  link: /IMG/title.png

hyiyan:
  enable: true

# Header & Footer的Nav链接
pages:
  Home:
    link: "/"
  Archive:
    link: "/archives/"
  Categories:
    link: "/categories/"
  Tags:
    link: "/tags/"
  About:
    link: "/about/"
  Links:
    link: "/links/"
  Project:
    link: "/open-source/"

#---------------------------
# Index
#---------------------------

# 首页文章排序
  # 默认的"1"代表单行，为白色一行的样式来陈列文章。
  # 也可以选择"2"，代表大图，蓝色的，抽取头图，适合文章图片较多的人士。(在文章Front-Matter里使用cover属性规定头图)
indexpp: 2

#---------------------------
# Links
#---------------------------

# 友情链接

links:
    - {
      title: 'Adkinsm Home',
      intro: 'Adkinsm 主页',
      link: 'https://www.adkinsm.top/',
      image: '/assets/images/favicon.png'
    }
    - {
      title: 'AxiomXS',
      intro: '老友',
      link: 'https://www.axiomxs.com/',
      image: 'https://s3.ax1x.com/2021/02/07/ytIFWF.png'
    }
    - {
      title: '小丫头片子',
      intro: '老有不老有的也不管了',
      link: '//www.cnblogs.com/xytpz',
      image: 'https://i.loli.net/2020/12/31/MDiPhGOCmzwHjsp.jpg'
    }
    - {
      title: 'ivampiresp',
      intro: '老有不老有的也不管了',
      link: '//ivampiresp.com',
      image: 'https://nwl.im/avatar'
    }
    - {
      title: 'JR BLOG',
      intro: '老有不老有的也不管了',
      link: '//blog.jrcloud.vip',
      image: 'https://gitee.com/jrcloud/cdn/raw/master/d.jpg'
    }
    - {
      title: '团子',
      intro: '老有不老有的也不管了',
      link: '//www.mikuchan.top/',
      image: 'https://blog-static.mikuchan.top/avatar.jpg?imageMogr2/thumbnail/!20p/format/webp/blur/1x0/quality/70/w/256/h/256'
    }
    - {
      title: 'FUTURD',
      intro: '老有不老有的也不管了',
      link: '//www.futurd.cn',
      image: 'https://cdn.jsdelivr.net/gh/FloppyDisk-FD/fdimg@master/images/Avatar.jpg'
    }
    - {
      title: 'Doge',
      intro: '老有不老有的也不管了',
      link: '//www.ltdoge.top',
      image: ''
    }
    - {
      title: '泰戈尔',
      intro: '老有不老有的也不管了',
      link: 'https://www.iftiger.com/',
      image: 'https://ittiger.top/%E5%A4%B4%E5%83%8F.jpg'
    }






#---------------------------
# 404
#---------------------------

page404:
  enable: true

#---------------------------
# Tags
#---------------------------

pagetags:
  enable: true

#---------------------------
# Categories
#---------------------------

pagecate:
  enable: true

#---------------------------
# Comments
#---------------------------

# 由于我使用Waline，所以我决定最先支持Waline
waline:
  enable: true
  serverURL: 'https://talk-blog.vercel.app/'
